controller_list:
  - name: fake_conbe_controller
    joints:
      - joint0
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      # - right_gripper_joint
      # - left_gripper_joint